services:
  discord-bot:
    build:
      context: ./discord-bot
      dockerfile: Dockerfile
    volumes:
      - ./discord-bot:/discord-bot
    env_file:
      - .env
    networks:
      - webnet

networks:
  webnet:
    driver: bridge